### ISSUE TITLE
backend worker dies

### ISSUE THREAD

**Issue by hellodario** [mukut03/ESG-BERT#4]
Hi, i have the same issue of an user here.
i opened this one in pytorch/serve

https://github.com/pytorch/serve/issues/991

thanks 
Dario

**Comment by hellodario** [comment]
Hi there just flagging the issue has been solved in the thread above!
thanks

**Comment by varun-sappa** [comment]
@hellodario can you please help me out. i'm still not able to run the code
